version: '3'

services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@file"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=google-auth-secured@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: traefik-forward-auth
    environment:
      - CLIENT_ID=<CLIENT_ID>
      - CLIENT_SECRET=<CLIENT_SECRET>
      - SECRET=<RANDOM-STRING>
      - INSECURE_COOKIE=true # if prod, switch to "false"
      - COOKIE_DOMAIN=example.com
      - DOMAINS=example.com
      - AUTH_HOST=auth.example.com
      - WHITELIST=<YOUR_MAIL_ADDRESS>
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=http"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.traefik-forward-auth.middlewares=https-redirect@file"
      - "traefik.http.routers.traefik-forward-auth-secure.entrypoints=https"
      - "traefik.http.routers.traefik-forward-auth-secure.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.traefik-forward-auth-secure.tls=true"
      - "traefik.http.routers.traefik-forward-auth-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-forward-auth-secure.middlewares=google-auth-secured@file"
      - "traefik.http.routers.traefik-forward-auth-secure.service=traefik-forward-auth"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true